//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C102575814Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C102575814Customer()
        {
            this.C102575814Sale = new HashSet<C102575814Sale>();
        }
    
        public int CustNo_ { get; set; }
        public string CustName { get; set; }
        public string CustAddress { get; set; }
        public int CustPcode { get; set; }
        public string InterestCode { get; set; }
    
        public virtual C102575814Interest C102575814Interest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C102575814Sale> C102575814Sale { get; set; }
    }
}
