//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADEntities1 : DbContext
    {
        public DADEntities1()
            : base("name=DADEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C102575814Customer> C102575814Customer { get; set; }
        public virtual DbSet<C102575814Interest> C102575814Interest { get; set; }
        public virtual DbSet<C102575814Record> C102575814Record { get; set; }
        public virtual DbSet<C102575814Sale> C102575814Sale { get; set; }
    }
}
