//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C102575814Sale
    {
        public System.DateTime DateRecorded { get; set; }
        public double Price { get; set; }
        public int CustNo_ { get; set; }
        public string RecordID { get; set; }
        public string InterestCode { get; set; }
    
        public virtual C102575814Customer C102575814Customer { get; set; }
        public virtual C102575814Record C102575814Record { get; set; }
    }
}
